
# target_abi must in [thumb,armeabi-v7a、arm64-v8a、x86、x86_64]
# toolchain_name must in [gcc、clang]
# stl_type must in [c++_static、c++_shared、none、system]
set(target_abi_list armeabi armeabi-v7a arm64-v8a x86 x86_64)
set(toolchain_name_list gcc clang)
set(stl_type_list c++_static c++_shared none system gnustl_static)

include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)


function(_set_android_toolchain_file toolchain_file)
    if (EXISTS ${NDK_HOME})
        set(CMAKE_TOOLCHAIN_FILE ${NDK_HOME}/build/cmake/android.toolchain.cmake CACHE STRING "for android.toolchain.cmake path")
    endif ()
    if (IS_DIRECTORY ${toolchain_file})
        if (EXISTS ${toolchain_file}/build/cmake/android.toolchain.cmake)
            set(CMAKE_TOOLCHAIN_FILE ${toolchain_file}/build/cmake/android.toolchain.cmake CACHE STRING "for android.toolchain.cmake path")
            message("-- set CMAKE_TOOLCHAIN_FILE to:${CMAKE_TOOLCHAIN_FILE}")
            return()
        endif ()
    endif ()
    if (EXISTS ${toolchain_file})
        get_filename_component(toolchain_file_name ${toolchain_file} NAME)
        if (${toolchain_file_name} STREQUAL "android.toolchain.cmake")
            set(CMAKE_TOOLCHAIN_FILE ${toolchain_file}/build/cmake/android.toolchain.cmake CACHE STRING "for android.toolchain.cmake path")
            message("-- set CMAKE_TOOLCHAIN_FILE to:${CMAKE_TOOLCHAIN_FILE}")
            return()
        endif ()
    endif ()
    message(WARNING "toolchain_file:${toolchain_file} is not android toolchain file,try find ndk home by env")
    find_ndk_path(android_ndk_home)
    if (EXISTS ${android_ndk_home}/build/cmake/android.toolchain.cmake)
        set(CMAKE_TOOLCHAIN_FILE ${toolchain_file}/build/cmake/android.toolchain.cmake CACHE STRING "for android.toolchain.cmake path")
        message("-- set CMAKE_TOOLCHAIN_FILE to:${CMAKE_TOOLCHAIN_FILE}")
        return()
    endif ()
    message(FATAL_ERROR "-- can not find android.toolchain.cmake file,please set [toolchain_file] to NDK home or android.toolchain.cmake")
endfunction()


function(_set_ndk_home _ndk_home)
    if (IS_DIRECTORY ${_ndk_home})
        if (EXISTS ${_ndk_home}/ndk-build.cmd OR EXISTS ${ndk_home}/ndk-build)
            set(ANDROID_NDK_HOME ${_ndk_home} CACHE STRING "for ndk home path")
            set_property(GLOBAL PROPERTY ANDROID_NDK_HOME ${_ndk_home})
            message("-- set NDK_HOME to: ${ANDROID_NDK_HOME}")
        endif ()
    else ()
        message(FATAL_ERROR "-- NDK_HOME:${_ndk_home} not a directory")
    endif ()
endfunction()


function(init_android_ndk ndk_home)
    if (DEFINED NDK_HOME)
        set(ndk_home ${NDK_HOME})
    elseif (NOT DEFINED ndk_home)
        find_program(NDK_BUILD_EXECUTABLE ndk-build)
        if (NDK_BUILD_EXECUTABLE)
            get_filename_component(NDK_BUILD_DIR ${NDK_BUILD_EXECUTABLE} DIRECTORY)
            message(STATUS "Found ndk-build at: ${NDK_BUILD_EXECUTABLE}")
            message(STATUS "ndk-build directory: ${NDK_BUILD_DIR}")
            set(ndk_home ${NDK_BUILD_DIR})
        else ()
            message(FATAL_ERROR "ndk-build not found. Please make sure the Android NDK is installed and the ndk-build command is in your PATH.")
        endif ()
    endif ()
    _set_ndk_home(${ndk_home})
    _set_android_toolchain_file(${ndk_home})
    file(READ "${ndk_home}/source.properties" ANDROID_NDK_SOURCE_PROPERTIES)
    set(ANDROID_NDK_REVISION_REGEX
            "^Pkg\\.Desc = Android NDK\nPkg\\.Revision = ([0-9]+)\\.([0-9]+)\\.([0-9]+)(-beta([0-9]+))?")
    if (NOT ANDROID_NDK_SOURCE_PROPERTIES MATCHES "${ANDROID_NDK_REVISION_REGEX}")
        message(SEND_ERROR "-- Failed to parse Android NDK revision: ${ANDROID_NDK}/source.properties.\n${ANDROID_NDK_SOURCE_PROPERTIES}")
    endif ()
    set(NDK_MAIN_VERSION ${CMAKE_MATCH_1} CACHE STRING "for NDK version value")
    message("-- Android NDK Major: ${NDK_MAIN_VERSION}")
    message("-- Android NDK Minor: ${CMAKE_MATCH_2}")
    message("-- Android NDK Build: ${CMAKE_MATCH_3}")
endfunction()


macro(config_toolchain_file)
    if (ANDROID_ABI STREQUAL armeabi)
        set(ANDROID_ARM_MODE thumb CACHE STRING "for ANDROID_ARM_MODE value")
        set(ANDROID_COMPILER_PREFIX arm-linux-androideabi${ANDROID_NATIVE_API_LEVEL})
    elseif (ANDROID_ABI STREQUAL armeabi-v7a)
        set(ANDROID_COMPILER_PREFIX armv7a-linux-androideabi${ANDROID_NATIVE_API_LEVEL})
        set(ANDROID_ARM_MODE arm CACHE STRING "for ANDROID_ARM_MODE value")
    elseif (ANDROID_ABI STREQUAL arm64-v8a)
        set(ANDROID_COMPILER_PREFIX aarch64-linux-android${ANDROID_NATIVE_API_LEVEL})
    elseif (ANDROID_ABI STREQUAL x86)
        #i686-linux-android23
        set(ANDROID_COMPILER_PREFIX i686-linux-android${ANDROID_NATIVE_API_LEVEL})
    elseif (ANDROID_ABI STREQUAL x86_64)
        #x86_64-linux-android22
        set(ANDROID_COMPILER_PREFIX x86_64-linux-android${ANDROID_NATIVE_API_LEVEL})
    else ()
        message("-- Invalid Android ABI: ${ANDROID_ABI}")
    endif ()
    message("-- ANDROID_COMPILER_PREFIX:${ANDROID_COMPILER_PREFIX}")
    message("-- NDK_MAIN_VERSION:${NDK_MAIN_VERSION}")
    if (NDK_MAIN_VERSION VERSION_LESS 19)
        message(STATUS "ndk version < 19")
        add_compile_options(--target=${ANDROID_COMPILER_PREFIX})
        set(CMAKE_CXX_FLAGS "--target=${ANDROID_COMPILER_PREFIX} ${CMAKE_CXX_FLAGS}")
    else ()
        if (${CMAKE_HOST_SYSTEM} MATCHES Windows)
            set(CMAKE_C_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/${ANDROID_COMPILER_PREFIX}-clang.cmd)
            message("-- set CMAKE_C_COMPILER:${CMAKE_C_COMPILER}")
            set(CMAKE_CXX_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/${ANDROID_COMPILER_PREFIX}-clang++.cmd)
            message("-- set CMAKE_CXX_COMPILER:${CMAKE_CXX_COMPILER}")
        else ()
            set(CMAKE_C_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/${ANDROID_COMPILER_PREFIX}-clang)
            message("-- set CMAKE_C_COMPILER:${CMAKE_C_COMPILER}")
            set(CMAKE_CXX_COMPILER ${ANDROID_TOOLCHAIN_ROOT}/bin/${ANDROID_COMPILER_PREFIX}-clang++)
            message("-- set CMAKE_CXX_COMPILER:${CMAKE_CXX_COMPILER}")
        endif ()
    endif ()
endmacro()



function(init_android_build target_abi api_level toolchain_name stl_type)
    set(CMAKE_SYSTEM_NAME "Android" CACHE STRING "for CMAKE_SYSTEM_NAME value")
    if (NOT ${target_abi} IN_LIST target_abi_list)
        message(FATAL_ERROR "-- unsupported target abi:${target_abi},target_abi must in ${target_abi_list}")
    endif ()
    if (NOT DEFINED target_abi)
        set(target_abi "armeabi-v7a")
    endif ()

    if (NOT DEFINED api_level)
        if (${target_abi} STREQUAL "armeabi-v7a" OR ${target_abi} STREQUAL "x86")
            set(api_level "19")
        elseif (${target_abi} STREQUAL "arm64-v8a" OR ${target_abi} STREQUAL "x86_64")
            set(api_level "21")
        else ()
            message(WARNING "api_level is not provided and cannot be inferred for target_abi:${target_abi}")
        endif ()
    endif ()
    if (NOT DEFINED toolchain_name)
        set(toolchain_name "clang")
    endif ()

    if (NOT DEFINED stl_type)
        set(stl_type "c++_static")
    endif ()

    #如果未设置架构
    if (NOT DEFINED ANDROID_ABI)
        set(ANDROID_ABI ${target_abi} CACHE STRING "for ANDROID_ABI value")
    endif ()
    #设置目标架构
    if (NOT ${toolchain_name} IN_LIST toolchain_name_list)
        message(FATAL_ERROR "-- unsupported toolchain name:${toolchain_name},toolchain name must in ${toolchain_name_list}")
    endif ()
    set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION ${toolchain_name} CACHE STRING "for CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION value")
    if (NOT　DEFINED　CMAKE_ANDROID_STL_TYPE)
        if (NOT ${stl_type} IN_LIST stl_type_list)
            message(FATAL_ERROR "-- unsupported stl type :${stl_type},stl type must in ${stl_type_list}")
        endif ()
        set(CMAKE_ANDROID_STL_TYPE ${stl_type} CACHE STRING "for CMAKE_ANDROID_STL_TYPE value")
    endif ()
    if (ANDROID_ABI STREQUAL armeabi)

        set(ANDROID_ARM_MODE thumb CACHE STRING "for ANDROID_ARM_MODE value")
    elseif (ANDROID_ABI STREQUAL armeabi-v7a)
        set(ANDROID_ARM_MODE arm CACHE STRING "for ANDROID_ARM_MODE value")
    endif ()

    set(ANDROID_STL ${stl_type} CACHE STRING "for CMAKE_ANDROID_STL_TYPE value")
    set(ANDROID_NATIVE_API_LEVEL ${api_level} CACHE STRING "for ANDROID_NATIVE_API_LEVEL value")
    set(ANDROID_PLATFORM "android-${api_level}" CACHE STRING "for ANDROID_PLATFORM value")
    if (CMAKE_HOST_SYSTEM_NAME STREQUAL Linux)
        set(ANDROID_HOST_TAG linux-x86_64)
    elseif (CMAKE_HOST_SYSTEM_NAME STREQUAL Darwin)
        set(ANDROID_HOST_TAG darwin-x86_64)
    elseif (CMAKE_HOST_SYSTEM_NAME STREQUAL Windows)
        set(ANDROID_HOST_TAG windows-x86_64)
    endif ()
    set(ANDROID_TOOLCHAIN_ROOT
            "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/${ANDROID_HOST_TAG}")
    message(STATUS "${ANDROID_TOOLCHAIN_ROOT}")
    if (NDK_MAIN_VERSION GREATER_EQUAL 25)
        config_toolchain_file()
    endif ()
endfunction()

macro(strip_target)
    message(STATUS "remove debug info")
    string(REPLACE " " ";" FLAGS_LIST ${CMAKE_C_FLAGS})
    #message("List after splitting: ${FLAGS_LIST}")
    list(REMOVE_ITEM FLAGS_LIST -g)
    list(APPEND FLAGS_LIST -g0)
    list(APPEND FLAGS_LIST -fno-rtti)
    list(APPEND FLAGS_LIST -fno-exceptions)
    list(APPEND FLAGS_LIST -ffunction-sections)
    list(APPEND FLAGS_LIST -fdata-sections)
    list(APPEND FLAGS_LIST -fvisibility=hidden)
    string(REPLACE ";" " " CMAKE_C_FLAGS "${FLAGS_LIST}")

    string(REPLACE " " ";" FLAGS_LIST ${CMAKE_CXX_FLAGS})
    #message("List after splitting: ${FLAGS_LIST}")

    list(REMOVE_ITEM FLAGS_LIST -g)
    list(APPEND FLAGS_LIST -g0)
    list(APPEND FLAGS_LIST -fno-rtti)
    list(APPEND FLAGS_LIST -fno-exceptions)
    list(APPEND FLAGS_LIST -ffunction-sections)
    list(APPEND FLAGS_LIST -fdata-sections)
    list(APPEND FLAGS_LIST -fvisibility=hidden)
    string(REPLACE ";" " " CMAKE_CXX_FLAGS "${FLAGS_LIST}")
    set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -Wl,--gc-sections -Wl,--strip-all")
    set(CMAKE_C_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -Wl,--gc-sections -Wl,--strip-all")

    get_property(EXECUTABLE_TARGETS DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY BUILDSYSTEM_TARGETS)

    foreach (EXECUTABLE_TARGET ${EXECUTABLE_TARGETS})
        message(STATUS "will strip ${EXECUTABLE_TARGET}")
        add_custom_command(TARGET ${EXECUTABLE_TARGET}
                POST_BUILD
                COMMAND ${CMAKE_STRIP} --strip-unneeded $<TARGET_FILE:${EXECUTABLE_TARGET}>
                COMMENT "Stripping executable ${EXECUTABLE_TARGET}"
        )
    endforeach ()
endmacro()


macro(unite_build_output)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/build/staticlibs/${ANDROID_ABI})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/build/jnilibs/${ANDROID_ABI})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/build/bin/${ANDROID_ABI})
endmacro()


